export const buttons = [
  { type: 'action', char: 'C' },
  { type: 'digit', char: '7' },
  { type: 'digit', char: '8' },
  { type: 'digit', char: '9' },
  { type: 'operand', char: '*' },
  { type: 'action', char: 'CE' },
  { type: 'digit', char: '4' },
  { type: 'digit', char: '5' },
  { type: 'digit', char: '6' },
  { type: 'operand', char: '/' },
  { type: 'digit', char: ')' },
  { type: 'digit', char: '1' },
  { type: 'digit', char: '2' },
  { type: 'digit', char: '3' },
  { type: 'operand', char: '-' },
  { type: 'digit', char: '(' },
  { type: 'digit', char: '.' },
  { type: 'digit', char: '0' },
  { type: 'operand', char: '+' },
  { type: 'operand', char: '=' },
  { type: 'operand', char: '%' },
]
