describe('Math operations and expression calculations', () => {
  beforeEach(() => {
    cy.visit('#/')
  })

  it('Calculates two digit expression with all operations', () => {
    cy.calculateTwoDigits('+', '7', false)
    cy.calculateTwoDigits('*', '12', false)
    cy.calculateTwoDigits('/', '0.75', false)
    cy.calculateTwoDigits('-', '-1', false)
    cy.calculateTwoDigits('%', '3', false)
  })

  it('Calculates negative numbers', () => {
    cy.calculateTwoDigits('+', '-7', true)
    cy.calculateTwoDigits('*', '12', true)
    cy.calculateTwoDigits('/', '0.75', true)
    cy.calculateTwoDigits('-', '1', true)
    cy.calculateTwoDigits('%', '-3', true)
  })

  it('Calculate natural numbers', () => {
    cy.calculateNaturalDigits('+', '5.7')
    cy.calculateNaturalDigits('*', '5.720')
    cy.calculateNaturalDigits('/', '0.295')
    cy.calculateNaturalDigits('-', '-3.100')
    cy.calculateNaturalDigits('%', '1.3')
  })

  it('Calculates simple expression', () => {
    cy.enterSimpleExpression()
    cy.get("[data-test-id='button-=']").click()
    cy.get('[data-test-id=display] p:last-child').should('have.text', '26')
  })

  it('Calculate expression with depth of brackets (1)', () => {
    cy.get("[data-test-id='button-(']").click()
    cy.get("[data-test-id='button-3']").click()
    cy.get("[data-test-id='button-+']").click()
    cy.get("[data-test-id='button-4']").click()
    cy.get("[data-test-id='button-*']").click()
    cy.get("[data-test-id='button-3']").click()
    cy.get("[data-test-id='button-)']").click()
    cy.get("[data-test-id='button-*']").click()
    cy.get("[data-test-id='button-(']").click()
    cy.get("[data-test-id='button-1']").click()
    cy.get("[data-test-id='button-2']").click()
    cy.get("[data-test-id='button--']").click()
    cy.get("[data-test-id='button-5']").click()
    cy.get("[data-test-id='button-)']").click()
    cy.get("[data-test-id='button-+']").click()
    cy.get("[data-test-id='button-3']").click()
    cy.get("[data-test-id='button-=']").click()
    cy.get('[data-test-id=display] p:last-child').should('have.text', '108')
  })

  it('Calculate expression with depth of brackets (3)', () => {
    cy.get("[data-test-id='button-(']").click()
    cy.get("[data-test-id='button-(']").click()
    cy.get("[data-test-id='button-(']").click()
    cy.get("[data-test-id='button-4']").click()
    cy.get("[data-test-id='button-*']").click()
    cy.get("[data-test-id='button-3']").click()
    cy.get("[data-test-id='button-)']").click()
    cy.get("[data-test-id='button-+']").click()
    cy.get("[data-test-id='button-4']").click()
    cy.get("[data-test-id='button-)']").click()
    cy.get("[data-test-id='button-/']").click()
    cy.get("[data-test-id='button-2']").click()
    cy.get("[data-test-id='button-)']").click()
    cy.get("[data-test-id='button-+']").click()
    cy.get("[data-test-id='button-7']").click()
    cy.get("[data-test-id='button-3']").click()
    cy.get("[data-test-id='button-=']").click()
    cy.get('[data-test-id=display] p:last-child').should('have.text', '81')
  })

  it('Calculate difficult expression with brackets', () => {
    cy.calculateDifficultExpression()
  })

  it('Calculate expression with negative inputs', () => {
    cy.get("[data-test-id='button-(']").click()
    cy.get("[data-test-id='button-1']").click()
    cy.get("[data-test-id='button-2']").click()
    cy.get("[data-test-id='button-*']").click()
    cy.get("[data-test-id='button-3']").click()
    cy.get("[data-test-id='button-)']").click()
    cy.get("[data-test-id='button-*']").click()
    cy.get("[data-test-id='negative']").click()
    cy.get("[data-test-id='button-3']").click()
    cy.get("[data-test-id='button-2']").click()
    cy.get("[data-test-id='button-+']").click()
    cy.get("[data-test-id='button-2']").click()
    cy.get("[data-test-id='button-*']").click()
    cy.get("[data-test-id='negative']").click()
    cy.get("[data-test-id='button-4']").click()
    cy.get("[data-test-id='button-4']").click()
    cy.get("[data-test-id='button-=']").click()
    cy.get('[data-test-id=display] p:last-child').should('have.text', '-1240')
  })
})